<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Наши специалисты");
?>

<?$APPLICATION->IncludeComponent(
    "bitrix:news",
    "personal",
    array(
        "COMPONENT_TEMPLATE" => "personal",
        "IBLOCK_TYPE" => "med_bit_ecommerce_s1",
        "IBLOCK_ID" => "9",
        "NEWS_COUNT" => "200",
        "SORT_BY1" => "ACTIVE_FROM",
        "SORT_ORDER1" => "DESC",
        "SORT_BY2" => "SORT",
        "SORT_ORDER2" => "ASC",
        "FILTER_NAME" => "",
        "CHECK_DATES" => "Y",
        "LIST_FIELD_CODE" => array(
            0 => "DETAIL_PICTURE",
            1 => "DATE_ACTIVE_FROM",
            2 => "ACTIVE_FROM",
            3 => "DATE_ACTIVE_TO",
            4 => "ACTIVE_TO",
            5 => "",
        ),
        "LIST_PROPERTY_CODE" => array(
            1 => "CODE_ICO",
            2 => "IB_CLINIC",
            3 => 'STR_SPECIAL'
        ),
        "DETAIL_URL" => "",
        "AJAX_MODE" => "N",
        "AJAX_OPTION_JUMP" => "N",
        "AJAX_OPTION_STYLE" => "Y",
        "AJAX_OPTION_HISTORY" => "N",
        "AJAX_OPTION_ADDITIONAL" => "",
        "CACHE_TYPE" => "A",
        "CACHE_TIME" => "36000000",
        "CACHE_FILTER" => "N",
        "CACHE_GROUPS" => "Y",
        "PREVIEW_TRUNCATE_LEN" => "",
        "ACTIVE_DATE_FORMAT" => "j M Y",
        "SET_TITLE" => "Y",
        "SET_BROWSER_TITLE" => "Y",
        "SET_META_KEYWORDS" => "Y",
        "SET_META_DESCRIPTION" => "Y",
        "SET_LAST_MODIFIED" => "N",
        "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
        "ADD_SECTIONS_CHAIN" => "N",
        "HIDE_LINK_WHEN_NO_DETAIL" => "N",
        "PARENT_SECTION" => "",
        "PARENT_SECTION_CODE" => "",
        "INCLUDE_SUBSECTIONS" => "Y",
        "DISPLAY_DATE" => "Y",
        "DISPLAY_NAME" => "Y",
        "DISPLAY_PICTURE" => "N",
        "DISPLAY_PREVIEW_TEXT" => "Y",
        "PAGER_TEMPLATE" => ".default",
        "DISPLAY_TOP_PAGER" => "N",
        "DISPLAY_BOTTOM_PAGER" => "N",
        "PAGER_TITLE" => "Новости",
        "PAGER_SHOW_ALWAYS" => "N",
        "PAGER_DESC_NUMBERING" => "N",
        "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
        "PAGER_SHOW_ALL" => "N",
        "PAGER_BASE_LINK_ENABLE" => "N",
        "SET_STATUS_404" => "N",
        "SHOW_404" => "N",
        "MESSAGE_404" => "",
        "TEMPLATE_THEME" => "blue",
        "MEDIA_PROPERTY" => "",
        "SLIDER_PROPERTY" => "",
        "SEARCH_PAGE" => "/search/",
        "USE_RATING" => "N",
        "USE_SHARE" => "N",
        "USE_SEARCH" => "N",
        "USE_RSS" => "N",
        "USE_CATEGORIES" => "N",
        "USE_REVIEW" => "N",
        "USE_FILTER" => "Y",
        "SEF_MODE" => "Y",
        "SEF_FOLDER" => "/personal/",
        "ADD_ELEMENT_CHAIN" => "N",
        "USE_PERMISSIONS" => "N",
        "LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
        "DETAIL_SET_CANONICAL_URL" => "N",
        "DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
        "DETAIL_FIELD_CODE" => array(
            0 => "DETAIL_PICTURE",
            1 => "DATE_ACTIVE_FROM",
            2 => "ACTIVE_FROM",
            3 => "DATE_ACTIVE_TO",
            4 => "ACTIVE_TO",
            5 => "",
        ),
        "DETAIL_PROPERTY_CODE" => array(
            1 => "CODE_ICO",
        ),
        "DETAIL_DISPLAY_TOP_PAGER" => "N",
        "DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
        "DETAIL_PAGER_TITLE" => "Страница",
        "DETAIL_PAGER_TEMPLATE" => "round",
        "DETAIL_PAGER_SHOW_ALL" => "Y",
        "FB_EVENT_MESSAGE_ID" => array(),
        "FB_USE_CAPTCHA" => "N",
        "FB_IBLOCK_TYPE" => "med_bit_ecommerce_s1",
        "FB_IBLOCK_ID" => "18",
        "FB_PROPERTY_CODES" => array(
            0 => "AUTHOR",
            1 => "EMAIL",
            2 => "TEL",
            3 => "MESSAGE",
        ),
        "FB_PROPERTY_CODES_REQUIRED" => array(
            0 => "AUTHOR",
            1 => "EMAIL",
            2 => "MESSAGE",
        ),
        "SEF_URL_TEMPLATES" => array(
            "news" => "",
            "section" => "#SECTION_CODE#/",
            "detail" => "#SECTION_CODE#/#ELEMENT_CODE#/",
        )
    ),
    false
);?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>