<? $APPLICATION->IncludeComponent(
    "bitrix:menu",
    "left_menu",
    Array(
        "ALLOW_MULTI_SELECT" => "N",
        "CHILD_MENU_TYPE" => "left",
        "COMPONENT_TEMPLATE" => ".default",
        "DELAY" => "N",
        "MAX_LEVEL" => "1",
        "MENU_CACHE_GET_VARS" => array(0 => "",),
        "MENU_CACHE_TIME" => "3600",
        "MENU_CACHE_TYPE" => "N",
        "MENU_CACHE_USE_GROUPS" => "Y",
        "ROOT_MENU_TYPE" => "left",
        "USE_EXT" => "N"
    )
); ?>
<? $APPLICATION->IncludeComponent(
    "bitrix:news.list",
    "service_menu",
    Array(
        "SERVICE_ID" => $arParams["SERVICE_ID"],
        "SERVICE_CODE" => $arParams["SERVICE_CODE"],
        "IBLOCK_TYPE" => "med_bit_ecommerce_s1",
        "IBLOCK_ID" => "16",
        "NEWS_COUNT" => 1000,
        "SORT_BY1" => "SORT",
        "SORT_ORDER1" => "ASC",
        "SORT_BY2" => "SORT",
        "SORT_ORDER2" => "ASC",
        "PROPERTY_CODE" => array(
            0 => "CODE_ICO",
            1 => "PRICE",
            2 => "DESCRIPTION",
            3 => "KEYWORDS",
            4 => "ICONIMG",
        ),
        "SET_TITLE" => "N",
        "SET_LAST_MODIFIED" => "N",
        "SET_STATUS_404" => "N",
        "SHOW_404" => "N",
        "FILE_404" => "N",
        "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
        "CACHE_TYPE" => "A",
        "CACHE_TIME" => "36000000",
        "CACHE_FILTER" => "N",
        "CACHE_GROUPS" => "N",
        "DISPLAY_TOP_PAGER" => "N",
        "DISPLAY_BOTTOM_PAGER" => "N",
        "PAGER_TITLE" => "",
        "PAGER_TEMPLATE" => "",
        "PAGER_SHOW_ALWAYS" => "N",
        "PAGER_DESC_NUMBERING" => "",
        "PAGER_DESC_NUMBERING_CACHE_TIME" => "",
        "PAGER_SHOW_ALL" => "N",
        "PAGER_BASE_LINK_ENABLE" => "",
        "PAGER_BASE_LINK" => "",
        "PAGER_PARAMS_NAME" => "",
        "DISPLAY_DATE" => "N",
        "DISPLAY_NAME" => "N",
        "DISPLAY_PICTURE" => "N",
        "DISPLAY_PREVIEW_TEXT" => "N",
        "PREVIEW_TRUNCATE_LEN" => "N",
        "ACTIVE_DATE_FORMAT" => "",
        "USE_PERMISSIONS" => "N",
        "GROUP_PERMISSIONS" => "N",
        "FILTER_NAME" => "",
        "HIDE_LINK_WHEN_NO_DETAIL" => "N",
        "CHECK_DATES" => "Y",
    )
); ?>
<? $APPLICATION->IncludeComponent(
    "bit-ecommerce:iblock.element.add.form",
    "",
    Array(
        "AJAX_MODE" => "Y",
        "AJAX_OPTION_JUMP" => "N",
        "DEFAULT_INPUT_SIZE" => "30",
        "DETAIL_TEXT_USE_HTML_EDITOR" => "N",
        "ELEMENT_ASSOC" => "CREATED_BY",
        "ELEMENT_ASSOC_PROPERTY" => "",
        "EVENT_MESSAGE_ID" => $arParams["EVENT_MESSAGE_ID"],
        "IBLOCK_ID" => $arParams["IBLOCK_ID"],
        "IBLOCK_TYPE" => $arParams["IBLOCK_TYPE"],
        "LEVEL_LAST" => "N",
        "LIST_URL" => "",
        "MAX_FILE_SIZE" => "0",
        "MAX_LEVELS" => "100000",
        "MAX_USER_ENTRIES" => "100000",
        "PREVIEW_TEXT_USE_HTML_EDITOR" => "N",
        "PROPERTY_CODES" => $arParams["PROPERTY_CODES"],
        "PROPERTY_CODES_REQUIRED" => $arParams["PROPERTY_CODES_REQUIRED"],
        "RESIZE_IMAGES" => "N",
        "SEF_MODE" => "N",
        "STATUS" => "INACTIVE",
        "STATUS_NEW" => "NEW",
        "TITLE_ELEMENT" => "Обратная связь из левой колонки",
        "USER_MESSAGE_ADD" => "Ваша завка успешно отправлена",
        "USER_MESSAGE_EDIT" => "Saved",
        "USE_CAPTCHA" => $arParams["USE_CAPTCHA"]
    )
); ?>